"""The Gazebo car's planner profile and driving corridor, derived from the design numbers.

The planner was written against the indoor robot (configs/sim/robot.yaml: 0.6 m/s, 0.25 m
wheelbase) and its corridor (configs/driving/corridor.yaml: image fractions set for a camera
0.18 m up and 15 deg down). Neither fits a car at 20 km/h with a dashcam 1.3 m up. Both car
files are derived here, never hand-tuned, and written by `python -m sim.gazebo.package`:

- **Profile** (configs/sim/car.yaml, `load_robot`'s format): the car of
  configs/sim/gazebo.yaml and the design camera of configs/project.yaml. `max_speed_mps` is
  the design speed, so the policy's cruise_speed of 1.0 is 20 km/h; `max_steer_rad` is the
  AckermannSteering limit, so a Command's steer means the same angle on the wire and on
  the wheels.
- **Corridor** (configs/driving/corridor_car.yaml): where the car's wheels will go, as the
  design camera sees it. The ground strip |y| <= W ahead of the camera projects through
  `core.geometry.project` onto a trapezoid exactly (straight ground lines stay straight
  through a pinhole), from the frame's bottom row (the near edge of view) up to the row of
  the look-ahead distance. Its rows and widths are image fractions, as `load_corridor` reads.

The distances come from configs/project.yaml's `sim:` design kinematics (latency, braking
and lateral acceleration, swerve, margin) and `edge.detect_range_m`, and from the policy's
N-of-M confirmation at the camera's rate. Each file carries its own derivation as comments.
This module computes; it does not decide what the planner does with the numbers.
"""

from __future__ import annotations

import math

from certain_road.core.geometry import ground_point, project

HEADER = (
    "Generated by sim/gazebo/package.py (sim/gazebo/derive.py) from configs/sim/gazebo.yaml,\n"
    "configs/project.yaml and configs/driving/. Do not edit: change those and regenerate."
)


def _camera(project_cfg: dict) -> dict:
    s = project_cfg["sim"]
    w, h, hfov = s["cam_w"], s["cam_h"], s["cam_fov_rad"]
    return {
        "w": w,
        "h": h,
        "hfov": hfov,
        "kw": {
            "f": (w / 2) / math.tan(hfov / 2),
            "cx": w / 2,
            "cy": h / 2,
            "cam_h": s["cam_height_m"],
            "pitch": math.radians(s["cam_pitch_deg"]),
        },
    }


def car_profile(gz: dict, project_cfg: dict) -> dict:
    """The car as `certain_road.sim.model.load_robot` reads a vehicle."""
    veh, s = gz["vehicle"], project_cfg["sim"]
    cam = _camera(project_cfg)
    return {
        "robot": {
            "wheelbase_m": veh["wheelbase_m"],
            "length_m": veh["chassis"]["length_m"],
            "width_m": veh["chassis"]["width_m"],
            "max_speed_mps": round(s["speed_kmh"] / 3.6, 6),
            "max_steer_rad": veh["steering"]["limit_rad"],
        },
        "camera": {
            "height_m": s["cam_height_m"],
            "pitch_rad": round(cam["kw"]["pitch"], 9),
            "hfov_rad": cam["hfov"],
            "img_w": cam["w"],
            "img_h": cam["h"],
        },
    }


def car_profile_yaml(gz: dict, project_cfg: dict) -> str:
    p = car_profile(gz, project_cfg)
    r, c = p["robot"], p["camera"]
    return "\n".join(
        [
            *(f"# {line}" for line in HEADER.splitlines()),
            "#",
            "# The Gazebo camera car (ros/certain_road_gz) as the planner's vehicle profile, in",
            "# configs/sim/robot.yaml's format. planner_node vehicle:=car selects it; RosTransport",
            "# turns each Command into /cmd_vel with it, and can_monitor_node reads the CAN",
            "# payload's normalised speed and steer back into m/s and rad with it.",
            "#   max_speed_mps = configs/project.yaml sim.speed_kmh / 3.6: cruise_speed 1.0 is the",
            "#                   design speed, 20 km/h",
            "#   max_steer_rad = configs/sim/gazebo.yaml vehicle.steering.limit_rad, the",
            "#                   AckermannSteering limit: steer 1.0 is full lock on the car",
            "",
            "robot:",
            f"  wheelbase_m: {r['wheelbase_m']}",
            f"  length_m: {r['length_m']}",
            f"  width_m: {r['width_m']}",
            f"  max_speed_mps: {r['max_speed_mps']}",
            f"  max_steer_rad: {r['max_steer_rad']}",
            "",
            "camera:                      # the design camera, configs/project.yaml sim:",
            f"  height_m: {c['height_m']}",
            f"  pitch_rad: {c['pitch_rad']}",
            f"  hfov_rad: {c['hfov_rad']}",
            f"  img_w: {c['img_w']}",
            f"  img_h: {c['img_h']}",
            "",
        ]
    )


def car_corridor(gz: dict, project_cfg: dict, decision: dict, robot_corridor: dict) -> dict:
    """The corridor's fields (`load_corridor`'s), plus `escape_lanes` and every number used."""
    s, veh = project_cfg["sim"], gz["vehicle"]
    cam = _camera(project_cfg)
    kw, w, h = cam["kw"], cam["w"], cam["h"]
    v = s["speed_kmh"] / 3.6
    half = veh["track_m"] / 2 + veh["wheel"]["width_m"] / 2 + s["margin_m"]
    confirm_s = decision["confirmation"]["required"] / gz["camera"]["rate_hz"]
    react = v * (s["latency_s"] + confirm_s)
    stop = react + v * v / (2 * s["a_brake"])
    swerve = react + v * math.sqrt(2 * s["swerve_m"] / s["a_lat"])
    decide = max(stop, swerve)
    far = project_cfg["edge"]["detect_range_m"]
    near_edge = ground_point(kw["cx"], h, **kw)[0]

    def row(d: float) -> float:
        return project(d, 0.0, **kw)[1] / h

    def half_width(d: float) -> float:
        return abs(project(d, half, **kw)[0] - kw["cx"]) / w

    return {
        "center_x": kw["cx"] / w,
        "top_y": row(far),
        "top_half_width": half_width(far),
        "bottom_y": 1.0,
        "bottom_half_width": half_width(near_edge),
        "min_overlap": robot_corridor["min_overlap"],
        "near_proximity": row(decide),
        "imminent_proximity": row(stop),
        "escape_lanes": (s["swerve_m"] + s["margin_m"]) / half,
        "_numbers": {
            "speed_mps": v,
            "half_width_m": half,
            "confirm_s": confirm_s,
            "react_m": react,
            "stop_m": stop,
            "swerve_m": swerve,
            "decide_m": decide,
            "far_m": far,
            "near_edge_m": near_edge,
        },
    }


def car_corridor_yaml(gz: dict, project_cfg: dict, decision: dict, robot_corridor: dict) -> str:
    c = car_corridor(gz, project_cfg, decision, robot_corridor)
    n, s, veh = c["_numbers"], project_cfg["sim"], gz["vehicle"]
    req = decision["confirmation"]["required"]

    def f(x: float, d: int = 4) -> str:
        return f"{x:.{d}f}"

    lines = [
        *(f"# {line}" for line in HEADER.splitlines()),
        "#",
        "# The driving corridor for the Gazebo car's design camera (1.3 m up, 10 deg down, HFOV",
        "# 1.2 rad, 1280x720). Same meaning and format as configs/driving/corridor.yaml, which",
        "# stays the indoor robot's; planner_node corridor:=car selects this one. It is NOT the",
        "# survey ROI (D049). Every number below is derived, none tuned:",
        "#",
        "# Width. The ground strip the car occupies, |y| <= W:",
        f"#   W = track/2 + tyre/2 + margin = {veh['track_m'] / 2} + {veh['wheel']['width_m'] / 2}"
        f" + {s['margin_m']} = {f(n['half_width_m'], 3)} m",
        "#   (configs/sim/gazebo.yaml vehicle; margin = configs/project.yaml sim.margin_m)",
        "#",
        "# Distances, at the design speed v = 20 km/h = "
        f"{f(n['speed_mps'], 3)} m/s (configs/project.yaml sim:)",
        f"#   confirmation  {req} frames at {gz['camera']['rate_hz']} Hz = "
        f"{f(n['confirm_s'], 3)} s (configs/driving/decision.yaml, D075/D088)",
        f"#   reaction      v (latency_s {s['latency_s']} + {f(n['confirm_s'], 3)}) = "
        f"{f(n['react_m'], 2)} m",
        f"#   stopping      reaction + v^2 / (2 a_brake {s['a_brake']}) = {f(n['stop_m'], 2)} m",
        f"#   swerving      reaction + v sqrt(2 swerve_m {s['swerve_m']} / a_lat {s['a_lat']}) = "
        f"{f(n['swerve_m'], 2)} m",
        f"#   decision      max(stopping, swerving) = {f(n['decide_m'], 2)} m: a hazard nearer",
        "#                 than this needs a manoeuvre now (NEAR); swerve_m 0.8 clears a 1.2 m",
        "#                 pothole (the generator's largest) by the tyre's half-width",
        f"#   look-ahead    edge.detect_range_m = {n['far_m']} m: the design's detection gate.",
        f"#                 From there to {f(n['decide_m'], 2)} m a hazard is FAR (WARNING: slow",
        "#                 and watch), so the manoeuvre starts at caution speed",
        f"#   near edge     the frame's bottom row meets the road {f(n['near_edge_m'], 2)} m ahead",
        "#",
        "# Rows (image fraction from the top, core.geometry.project of the distance on the axis)",
        "# and half-widths (fraction of image width, of y = W at that distance):",
        "center_x: " + f(c["center_x"]) + "   # the camera sits on the car's centre line",
        "top_y: " + f(c["top_y"]) + "   # " + f"{n['far_m']} m",
        "top_half_width: " + f(c["top_half_width"]) + f"   # W at {n['far_m']} m",
        "bottom_y: "
        + f(c["bottom_y"])
        + f"   # the frame's bottom row, {f(n['near_edge_m'], 2)} m",
        "bottom_half_width: " + f(c["bottom_half_width"]) + f"   # W at {f(n['near_edge_m'], 2)} m",
        "",
        "# As configs/driving/corridor.yaml: the same in-path rule.",
        "min_overlap: " + f(c["min_overlap"], 2),
        "",
        "# Urgency rows. NEAR from the decision distance, IMMINENT from the stopping distance.",
        "near_proximity: " + f(c["near_proximity"]) + f"   # {f(n['decide_m'], 2)} m",
        "imminent_proximity: " + f(c["imminent_proximity"]) + f"   # {f(n['stop_m'], 2)} m",
        "",
        "# Escape lanes, in corridor half-widths: the strip the car moves into when it swerves,",
        f"# (swerve_m + margin) / W = ({s['swerve_m']} + {s['margin_m']}) /"
        f" {f(n['half_width_m'], 3)}. A pothole there blocks that side.",
        "escape_lanes: " + f(c["escape_lanes"]),
        "",
    ]
    return "\n".join(lines)
