"""Write the generated files: ros/certain_road_gz's data, and the car's planner configs.

    python -m sim.gazebo.package           # rewrite them
    python -m sim.gazebo.package --check   # exit 1 if a committed file differs from the config

The package is installed and run where only ROS 2 Jazzy and Gazebo Harmonic exist (the
Jetson, or a separate x86 PC running the simulation), so it cannot read this repository's
configs at run time. Its car model, bridge table and frame file are therefore generated
here and committed; tests/test_gazebo_package.py fails when they drift from the config.
The car's planner profile and corridor (configs/sim/car.yaml, configs/driving/
corridor_car.yaml, sim/gazebo/derive.py) are generated the same way, beside the robot's.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from certain_road.core.paths import repo_root
from sim.gazebo.derive import car_corridor_yaml, car_profile_yaml
from sim.gazebo.vehicle import camera_pose, vehicle_sdf
from sim.mujoco.road import load_config
from sim.mujoco.scene import design_camera

CONFIG = repo_root() / "configs/sim/gazebo.yaml"
PACKAGE = repo_root() / "ros/certain_road_gz"
MODEL_DIR = "models/certain_road_car"
HEADER = "Generated by sim/gazebo/package.py from configs/sim/gazebo.yaml. Do not edit."

# ros_gz_bridge types per topic key: the message pairs ros_gz_bridge supports for each.
BRIDGE_TYPES = {
    "clock": ("rosgraph_msgs/msg/Clock", "gz.msgs.Clock", "GZ_TO_ROS"),
    "image": ("sensor_msgs/msg/Image", "gz.msgs.Image", "GZ_TO_ROS"),
    "camera_info": ("sensor_msgs/msg/CameraInfo", "gz.msgs.CameraInfo", "GZ_TO_ROS"),
    "cmd_vel": ("geometry_msgs/msg/Twist", "gz.msgs.Twist", "ROS_TO_GZ"),
    "odom": ("nav_msgs/msg/Odometry", "gz.msgs.Odometry", "GZ_TO_ROS"),
    "wheel_odom": ("nav_msgs/msg/Odometry", "gz.msgs.Odometry", "GZ_TO_ROS"),
    "tf": ("tf2_msgs/msg/TFMessage", "gz.msgs.Pose_V", "GZ_TO_ROS"),
    "joint_states": ("sensor_msgs/msg/JointState", "gz.msgs.Model", "GZ_TO_ROS"),
}


def load() -> dict:
    return yaml.safe_load(CONFIG.read_text())


def bridge_yaml(gz: dict) -> str:
    rows = []
    for key, (ros_type, gz_type, direction) in BRIDGE_TYPES.items():
        t = gz["topics"][key]
        rows.append(
            {
                "ros_topic_name": t["ros"],
                "gz_topic_name": t["gz"],
                "ros_type_name": ros_type,
                "gz_type_name": gz_type,
                "direction": direction,
            }
        )
    return f"# {HEADER}\n" + yaml.safe_dump(rows, sort_keys=False)


def car_yaml(gz: dict, design: dict) -> str:
    """What the launch file needs besides the SDF: names, frames, the camera's mounting."""
    pose = [round(float(v), 9) for v in camera_pose(gz, design)]
    doc = {
        "model_name": gz["vehicle"]["name"],
        "model_sdf": f"{MODEL_DIR}/model.sdf",
        "frames": {
            "odom": gz["frames"]["odom"],
            "base": gz["frames"]["base"],
            "camera": gz["camera"]["frame"],
            "optical": gz["camera"]["optical_frame"],
        },
        "spawn_z_m": round(gz["vehicle"]["cg_height_m"] + gz["vehicle"]["spawn"]["drop_m"], 6),
        "camera_xyz": pose[:3],
        "camera_rpy": pose[3:],
        "camera_default": {
            "w": design["w"],
            "h": design["h"],
            "rate_hz": gz["camera"]["rate_hz"],
        },
        "camera_low": gz["camera"]["low"],
    }
    return f"# {HEADER}\n" + yaml.safe_dump(doc, sort_keys=False)


def model_config(gz: dict) -> str:
    return (
        '<?xml version="1.0"?>\n'
        f"<!-- {HEADER} -->\n"
        "<model>\n"
        "  <name>certain_road_car</name>\n"
        "  <version>1.0</version>\n"
        '  <sdf version="1.10">model.sdf</sdf>\n'
        "  <description>certain-road camera car: Ackermann steering, spring-damper "
        "suspension, the design dashcam.</description>\n"
        "</model>\n"
    )


def generated() -> dict[str, str]:
    """Repository-relative path -> the text it must hold."""
    gz = load()
    look = load_config(gz["look"])
    design = design_camera()
    project_cfg = yaml.safe_load((repo_root() / "configs/project.yaml").read_text())
    decision = yaml.safe_load((repo_root() / "configs/driving/decision.yaml").read_text())
    robot_corridor = yaml.safe_load((repo_root() / "configs/driving/corridor.yaml").read_text())
    sdf = vehicle_sdf(
        gz, design, look["camera_effects"]["sensor_noise"], project_cfg["sim"]["a_brake"]
    )
    sdf = sdf.replace("<sdf ", f"<!-- {HEADER} -->\n<sdf ", 1)
    pkg = "ros/certain_road_gz"
    return {
        f"{pkg}/{MODEL_DIR}/model.sdf": sdf,
        f"{pkg}/{MODEL_DIR}/model.config": model_config(gz),
        f"{pkg}/config/bridge.yaml": bridge_yaml(gz),
        f"{pkg}/config/car.yaml": car_yaml(gz, design),
        "configs/sim/car.yaml": car_profile_yaml(gz, project_cfg),
        "configs/driving/corridor_car.yaml": car_corridor_yaml(
            gz, project_cfg, decision, robot_corridor
        ),
    }


def stale(root: Path | None = None) -> list[str]:
    root = root or repo_root()
    return [
        p
        for p, text in generated().items()
        if not (root / p).is_file() or (root / p).read_text() != text
    ]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if args.check:
        bad = stale()
        print("stale: " + ", ".join(bad) if bad else "package files match the config")
        sys.exit(1 if bad else 0)
    for path, text in generated().items():
        out = repo_root() / path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
